executor: slurm
jobs: 40
use-conda: true
conda-frontend: conda
rerun-triggers: mtime
keep-going: true
printshellcmds: true

default-resources:
  slurm_partition: serial
  runtime: 600
  slurm_extra: "--qos=serial -N 1 -n 1"
